AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - Gemfile
    - Gemfile.lock
    - vendor/**/*

Gemspec/RequireMFA:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/SpecialGlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
